name = "mihayos"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[vars]
ADMIN_USERNAME = "mihayosafaris"
ADMIN_PASSWORD = "admin"

[[d1_databases]]
binding = "DB"
database_name = "mihayos-safaris"
database_id = "e140ff0e-4a7a-4779-b213-6e728ed9e30d"
